version: 2 

models: 
  - name: dim_customers
    columns:
    - name: customer_id
      tests:
        - not_null
        - unique
  - name: dim_employees
    columns:
    - name: employees_id
      tests:
        - not_null
        - unique